theme: jekyll-theme-minimal
logo: "/assets/img/logo.png"
show_downloads: true
github:
  zip_url: "https://github.com/tungkradle/dase-theme/releases/download/v1.1/dase-theme.zip"
  tar_url: "https://github.com/tungkradle/dase-theme/tarball/master"